---
mode: development
swagger:
  host: localhost:7745
  scheme: http
web:
  port: 7745
  host:
database:
  driver: sqlite3
  sqlite-url: ./ent.db?_fk=1
logger:
  level: debug
  file: api.log
mailer:
  host: smtp.example.com
  port: 465
  username:
  password:
  from: example@email.com
