on:
  push:
    branches: [main]
    paths:
      - "**.ts"
      - "**.vue"
  pull_request:
    branches: [main]
    paths:
      - "**.ts"
      - "**.vue"

jobs:
  Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Vitest
        run: pnpm test:ci
        working-directory: frontend
