name: Build Nightly

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: login to container registry
        run: docker login ghcr.io --username hay-kot --password $CR_PAT
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: build the image
        run: |
          cd backend && docker build --push --no-cache \
            --tag ghrc.io/hay-kot/homebox:nightly \
            --build-arg COMMIT=$(git rev-parse HEAD) \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
