name: Update Currencies

on:
  push:
    branches:
      - main

jobs:
  update-currencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run currency fetch script
        run: python .github/scripts/update_currencies.py

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create a new branch
          git checkout -b update-currencies
          git add backend/internal/core/currencies/currencies.json
          git commit -m "Update currencies.json"

          # Fetch the latest changes from the remote
          git fetch origin main
          git rebase origin/main  # Rebase your changes onto the latest main branch

          # Push the new branch to the remote
          git push --set-upstream origin update-currencies
          
          # Create a pull request
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d '{"title": "Update currencies", "head": "update-currencies", "base": "main"}' \
               https://api.github.com/repos/${{ github.repository }}/pulls

      - name: Notify no changes
        if: env.changes == 'false'
        run: echo "Currencies up-to-date with API, skipping commit."
